### ISSUE TITLE
Unclear reasoning behind solution

### ISSUE THREAD

**Issue by zapatos24** [learn-co-curriculum/dsc-permutations-and-factorials-lab#1]
I'm noticing I'm not the only one confused on this, but for the diff_fhses solution under b)event space, it's unclear (for someone who's trying to grasp the math concepts) how that solution was derived. From the formulas we've been presented so far, what do the 6! and 4! numerator and denominator represent?

In general too, some more commented out notation about why the solution is what it is in this section would be super helpful.

**Comment by mas16** [comment]
Hi zapatos24, thanks for the feedback! Some comments have been added to the solution branch to explain the results. The solution branch also contains a more in-depth explanation for the solution to the b) Event Space section as well.

**Comment by zapatos24** [comment]
Sweet, thanks!

Best,

Jeremy
__________________________
*Jeremy T. Owens*
*Data Scientist*
*757-903-8024*
